### ISSUE TITLE
How to send File Local to Group or User?

### ISSUE THREAD

**Issue by akunzz** [Its-VrxxDev/zlapi#2]
As the same sendLocalImage

**Comment by akunzz** [comment]
Go away, you virus bitch

**Comment by Its-VrxxDev** [comment]
Hi @akunzz , Currently the module only supports sending files by url using function `sendRemoteFile` . Or you can also upload local file to a host like **github, 000webhost, ...** and use that url to send the file.
> Otherwise, we will update this feature soon !

**Comment by akunzz** [comment]
thanks so much!

**Comment by Its-VrxxDev** [comment]
If there are no further questions, I will close this issue.
