### ISSUE TITLE
Fixed login problem

### ISSUE THREAD

**Issue by netrotion** [Its-VrxxDev/zlapi#8]
---

## Description of the problem
Get bad requests when login

## Code to reproduce
```py
# Example code
from zlapi import ZaloAPI
imei = "<your imei>"
cookies = "<your cookies>"
client = ZaloAPI("</>", "</>", imei, cookies)
```

## Traceback
```
# Traceback Login Error
```

## Environment information
- Python version
- `zlapi` version
- If relevant, output from `python -m pip list`

## Solution
just paste the following code
```
response = cls._get("https://wpa.chat.zalo.me/api/login/getLoginInfo", params=params) #replace in line 60 at _state.py
data["data"]["secret_key"] = data["data"]["zpw_enk"] #paste in line 66
```

**Comment by anhwaivo** [comment]
tysm man!

**Comment by Its-VrxxDev** [comment]
Now you can delete and re install zlapi git version
